module.exports = [
  "Life loves me!",
  "All is well in my world. Everything is working out for my highest good. Out of this situation only good will come. I am safe!",
  "It’s only a thought, and a thought can be changed.",
  "The point of power is always in the present moment.",
  "Every thought we think is creating our future.",
  "I am in the process of positive change.",
  "I am comfortable looking in the mirror, saying, “I love you, I really love you.”",
  "It is safe to look within.",
  "I forgive myself and set myself free.",
  "As I say yes to life, life says yes to me.",
  "I now go beyond other people’s fears and limitations.",
  "I am Divinely guided and protected at all times.",
  "I claim my power and move beyond all limitations.",
  "I trust the process of life.",
  "I am deeply fulfilled by all that I do.",
  "We are all family, and the planet is our home.",
  "As I forgive myself, it becomes easier to forgive others.",
  "I am willing to let go.",
  "Deep at the center of my being is an infinite well of love.",
  "I prosper wherever I turn.",
  "I welcome miracles into my life.",
  "Whatever I need to know is revealed to me at exactly the right time.",
  "I am loved, and I am at peace.",
  "My happy thoughts help create my healthy body.",
  "Life supports me in every possible way.",
  "My day begins and ends with gratitude.",
  "I listen with love to my body’s messages.",
  "The past is over.",
  "Only good can come to me.",
  "I am beautiful, and everybody loves me.",
  "Everyone I encounter today has my best interests at heart.",
  "I always work with and for wonderful people. I love my job.",
  "Filling my mind with pleasant thoughts is the quickest road to health.",
  "I am healthy, whole, and complete.",
  "I am at home in my body.",
  "I devote a portion of my time to helping others. It is good for my own health.",
  "I am greeted by love wherever I go.",
  "Wellness is the natural state of my body. I am in perfect health.",
  "I am pain free and totally in sync with life.",
  "I am very thankful for all the love in my life. I find it everywhere.",
  "I know that old, negative patterns no longer limit me. I let them go with ease.",
  "In the infinity of life where I am, all is perfect, whole, and complete.",
  "I trust my intuition. I am willing to listen to that still, small voice within.",
  "I am willing to ask for help when I need it.",
  "I forgive myself for not being perfect.",
  "I honor who I am.",
  "I attract only healthy relationships. I am always treated well.",
  "I do not have to prove myself to anyone.",
  "I come from the loving space of my heart, and I know that love opens all doors.",
  "I am in harmony with nature.",
  "I welcome new ideas.",
  "Today, no person, place, or thing can irritate or annoy me. I choose to be at peace.",
  "I am safe in the Universe and All Life loves and supports me.",
  "I experience love wherever I go.",
  "I am willing to change.",
  "I drink lots of water to cleanse my body and mind.",
  "I choose to see clearly with the eyes of love.",
  "I cross all bridges with joy and ease.",
  "I release all drama from my life.",
  "Loving others is easy when I love and accept myself.",
  "I balance my life between work, rest, and play.",
  "I return to the basics of life: forgiveness, courage, gratitude, love, and humor.",
  "I am in charge, I now take my own power back.",
  "My body appreciates how I take care of it.",
  "I spend time with positive, energetic people.",
  "The more peaceful I am inside, the more peace I have to share with others.",
  "Today is a sacred gift from Life.",
  "I have the courage to live my dreams.",
  "I release all negative thoughts of the past and all worries about the future.",
  "I forgive everyone in my past for all perceived wrongs. I release them with love.",
  "I only speak positively about those in my world. Negativity has no part in my life.",
  "We are all eternal spirit.",
  "I act as if I already have what I want—it’s an excellent way to attract happiness in my life.",
  "I enjoy the foods that are best for my body.",
  "My life gets better all the time.",
  "It is safe for me to speak up for myself.",
  "I live in the paradise of my own creation.",
  "Perfect health is my Divine right, and I claim it now.",
  "I release all criticism.",
  "I am on an ever-changing journey.",
  "I am grateful for my healthy body. I love life.",
  "Love flows through my body, healing all dis-ease.",
  "My income is constantly increasing.",
  "My healing is already in process.",
  "There is always more to learn.",
  "I now live in limitless love, light, and joy.",
  "I become more lovable every day.",
  "It is now safe for me to release all of my childhood traumas and move into love.",
  "I deserve all that is good.",
  "I am constantly discovering new ways to improve my health.",
  "Love is all there is!",
  "My life gets more fabulous every day.",
  "Today I am at peace.",
  "Loving others is easy when I love and accept myself.",
  "I have the perfect living space.",
  "I have compassion for all.",
  "I trust the Universe to help me see the good in everything and in everyone.",
  "I love my family members just as they are. I do not try to change anyone.",
  "There is plenty for everyone, and we bless and prosper each other.",
  "I love and approve of myself.",
  "Life is good, and so it is!",
  "I appreciate the gift of each new day and the opportunities it brings.",
  "Everything I do today, I choose to do.",
  "All is well. I have time for everything I need to do today.",
  "Every day, abundance flows into my life in surprising and miraculous ways.",
  "My awareness grows day by day.",
  "I live in the best of all possible worlds.",
  "I greet this new day with gratitude, hopefulness, and anticipation.",
  "I appreciate the simple joys that surround me every day.",
  "Each day, I find new reasons to be thankful and appreciative.",
  "I am open to the lessons that this day will teach me.",
  "I am worthy of love and respect.",
  "I embrace my unique qualities and celebrate who I am.",
  "I love and accept myself unconditionally.",
  "I accept my body as it is.",
  "I choose to honor my beauty, my strength, and my uniqueness.",
  "Accepting myself as I am is the first step to changing, growing, and evolving.",
  "I am deserving of happiness and fulfillment in all areas of my life.",
  "I release the need for comparison and embrace my individuality.",
  "I trust myself to make decisions that align with my highest good.",
  "I am enough, just as I am, and I am worthy of love and success.",
  "I practice self-compassion and extend it to others with kindness and understanding.",
  "I can make peace with errors so they can help me get better.",
  "I forgive myself for not being perfect.",
  "I give myself credit every time I do something that makes me happy.",
  "I am continually improving.",
  "May my heart be filled with feelings of kindness and compassion for myself.",
  "May my heart be filled with feelings of kindness and compassion for others.",
  "I am grateful for the choices I have made as they have brought me to who I am today.",
  "I embrace my imperfections and treat myself with kindness and understanding.",
  "I offer myself gentle forgiveness and allow mistakes to be stepping stones towards growth and learning.",
  "I am confident in my abilities to achieve my goals.",
  "I am capable of handling any challenge that comes my way.",
  "I believe in myself and my inner strength.",
  "Whatever I need to know is revealed to me at exactly the right time.",
  "I trust the process of life.",
  "I have the courage to live my dreams.",
  "I step outside of my comfort zone with courage, knowing that growth and success await.",
  "I embrace my unique gifts and talents, knowing that they contribute to my success.",
  "I am worthy of all the opportunities and abundance that come my way.",
  "I am confident in my ability to handle whatever comes my way.",
  "I am open to receiving abundance in all areas of my life.",
  "I attract opportunities for success and financial prosperity.",
  "I am grateful for the abundance that flows into my life.",
  "I embrace a mindset of abundance, and I celebrate the success and achievements of others.",
  "I release any scarcity mindset and embrace the belief that there is always more than enough for everyone.",
  "I joyfully and unconditionally give and receive abundance in all forms.",
  "I am grateful for the abundance that surrounds me and appreciate the blessings in my life.",
  "I release any limiting beliefs about money and replace them with thoughts of prosperity and abundance.",
  "I am grateful for the abundance that comes to me in expected and unexpected ways.",
  "I attract prosperous opportunities that align with my passion and purpose.",
  "I am grateful for my health and well-being.",
  "I make choices that nourish and support my well-being.",
  "I am deserving of vibrant health and vitality.",
  "I nourish my mind and body with what I need to be healthy today.",
  "I am healthy, whole, and complete.",
  "I balance my life between work, rest, and play.",
  "I prioritize self-care and make time for activities that nurture my physical and mental well-being.",
  "I listen to my body’s wisdom and provide it with the love, care, and attention it deserves.",
  "I am in tune with my body’s needs, and I honor its signals for rest, nourishment, and movement.",
  "I release all burdens, anxieties, and fears. Only good can come to me.",
  "I attract loving and supportive relationships into my life.",
  "I communicate openly and honestly, creating deep connections.",
  "I am deserving of love and have healthy, fulfilling relationships.",
  "I am surrounded by positive and uplifting people who support and inspire me.",
  "I am worthy of experiencing deep and authentic connections in my relationships.",
  "I communicate my needs and boundaries with love, respect, and assertiveness.",
  "I attract harmonious relationships that are based on mutual trust, understanding, and growth.",
  "I radiate love and compassion, creating an inviting space for nurturing and meaningful connections.",
  "I am open to giving and receiving love in all its forms, allowing it to flow freely in my relationships.",
  "I release past relationship patterns that no longer serve me and embrace new opportunities for love and connection.",
  "I attract success and prosperity through my efforts.",
  "I am capable of achieving my goals and fulfilling my dreams.",
  "I embrace challenges as opportunities for growth and success.",
  "I am willing to ask for help when I need it.",
  "I am fully aligned with my goals and take inspired actions to manifest them.",
  "I have an unwavering belief in my abilities.",
  "I attract abundant opportunities that propel me towards my desired level of success.",
  "I am resilient and persistent in the pursuit of my dreams, never giving up on my vision.",
  "I embrace a growth mindset and constantly seek new knowledge and skills to support my success.",
  "I celebrate the achievements and milestones along my journey, knowing that each step is significant.",
  "I am grateful for the good in my life.",
  "I appreciate the present moment and find joy in the simple things.",
  "I attract more reasons to be grateful every day.",
  "I find and enjoy the simple pleasures life is offering right now.",
  "I am thankful for the kindness and generosity I receive.",
  "I express gratitude for the lessons and growth I experience.",
  "I am grateful for my health and well-being.",
  "I am thankful for the abundance of love and support that surrounds me.",
  "I express gratitude for the beauty and wonder of the world around me.",
  "I appreciate the little things that bring me happiness and joy each day.",
  "I am grateful for the opportunities that come my way, both big and small.",
  "I am constantly evolving and growing into the best version of myself.",
  "I embrace change and step outside my comfort zone to grow.",
  "I am open to learning, expanding, and transforming my life.",
  "Changing is not a matter of doing, it is a matter of accepting.",
  "I allow my pain and fear to be my teachers.",
  "I am grateful for the challenges that help me become stronger.",
  "I embrace change and seek to learn new lessons from it.",
  "I do not fail. I either win or I learn.",
  "I appreciate the abundance of opportunities for personal growth.",
  "I am willing to change.",
  "I choose to see the positive aspects of every situation.",
  "I am grateful for the past experiences that have shaped me into who I am today.",
  "I am on an ever-changing journey.",
  "I embrace the practice of mindfulness, allowing it to guide me towards greater awareness and inner peace.",
  "I am fully present in this moment, embracing it with an open heart and mind.",
  "I observe my thoughts and emotions with curiosity and non-judgment.",
  "I gently and easily return to the present moment.",
  "I observe my emotions without getting attached to them.",
  "I am grounded in the experience of the present moment.",
  "I pay attention to the present moment with compassion, curiosity, and acceptance.",
  "I am thankful for the present moment and all it has to offer.",
  "I approach each experience with a beginner’s mind, open to new possibilities.",
  "I anchor myself in the present moment, finding peace and clarity.",
  "I appreciate the present moment and find joy in the simple things.",
  "My intuition is always reliable. I trust my gut.",
  "I am happy and confident.",
  "I cherish all of my life.",
  "The Universe has my back at all times.",
  "My soul radiates love, peace, and confidence.",
  "I am crushing this thing called life.",
  "I honor myself and my place in this world.",
  "I speak with confidence and convince others to see my point.",
  "My confidence is strong and can't be crushed by others.",
  "I am one awesome person and can do all I attempt.",
  "I learn new skills easily.",
  "I swim easily through life's waves and dance in the rain.",
  "I bounce back easily when things don't go as planned.",
  "I know what I need to say inside and out and won't falter.",
  "I am my favorite person.",
  "Dead ends just create a place to turn around.",
  "I willingly accept my role in forging a new path.",
  "I naturally gravitate toward my best choice.",
  "Confidence is my birthright.",
  "I have a good sense of humor and cheer others up easily.",
  "I create the path I walk and will do so confidently.",
  "People are drawn to me.",
  "I am a good person who deserves all the good I receive.",
  "I always see the best in myself and others.",
  "I am self-sufficient in all areas of my life.",
  "I don't overthink my choices and interactions.",
  "Confidence is my strongest trait.",
  "I have no need to fear failing – or succeeding.",
  "I have no need to second-guess myself.",
  "I learn from my mistakes and see them as tools for growth.",
  "I am proud to be me.",
  "I am smart and capable of achieving whatever I want.",
  "I am an inspiration to others.",
  "I am a natural leader and others willingly follow my lead.",
  "I am persistent and don't give up.",
  "I am more than enough.",
  "I bring my best to the table.",
  "I willingly share my gifts with others.",
  "I won't allow others to limit me.",
  "My inner light shines brightly.",
  "My past does not define me. I live in the now.",
  "I deserve the compliments I receive.",
  "I attract only those that radiate with my energy.",
  "I am my biggest cheerleader.",
  "I navigate detours effortlessly.",
  "I am safe and protected.",
  "I react with empathy and patience and deserve the same treatment.",
  "I relish opportunities to learn new things.",
  "I deserve the best treatment and will accept nothing less.",
  "I am the best person for me to rely on.",
  "I can easily get everything I need.",
  "I trust myself completely.",
  "I am the most qualified person to decide for me.",
  "My intuition is something to be trusted.",
  "I make well-informed decisions.",
  "I am the creator of my own world.",
  "I am motivated to succeed.",
  "The unknown is just another adventure.",
  "I walk confidently with my head held high.",
  "I am a kind and supportive person.",
  "I am fun to spend time with.",
  "My imperfections make me unique.",
  "I can cut ties in toxic relations without guilt.",
  "My journey is worth the destination.",
  "Expressing my emotions is easy.",
  "My true self is worthy of showing the world.",
  "I need only my own validation, not that of others.",
  "I banish negativity from my thoughts.",
  "I am stronger than what makes me afraid.",
  "I can get around every roadblock.",
  "I celebrate all I have done and will do.",
  "I let go of anxiety and self-doubt.",
  "My body and mind are stress-free.",
  "I empower myself and others.",
  "I release all self-judgment and forgive myself.",
  "Others have confidence in me.",
  "The world needs me and I will meet that need.",
  "I am calm and collected.",
  "I am becoming my greatest self.",
  "I can conquer all I set out to do.",
  "I choose to take a leap of faith.",
  "I choose to accept love and praise.",
  "My presence makes a difference in the world.",
  "I have unlimited potential.",
  "Others respect my boundaries.",
  "I honor my boundaries.",
  "I will reach my goals.",
  "I love interacting with people and they love me.",
  "I am courageous.",
  "I can let negativity roll off me without effort.",
  "Others see my confidence.",
  "I appreciate each and every part of myself.",
  "I am intelligent and can show this with confidence.",
  "I have come far and I celebrate all my successes.",
  "Life is an adventure and I learn more every day.",
  "I give my best at all times.",
  "I am flexible and can embrace change without fear.",
  "I am beautiful inside and out.",
  "I am strong enough to get through any and all adversity with grace.",
  "I am ready and willing to step out of my comfort zone.",
  "I am blessed in so many ways.",
  "I deserve to succeed and have earned every success I have achieved.",
  "People respect me and seek out my advice.",
  "I make my needs known without fear.",
  "I am comfortable speaking up no matter what the situation.",
  "I am worthy of all I ask for and receive from the Universe.",
  "I am whole and complete just as I am.",
  "I am loved and appreciated.",
  "I have claimed my power and will not give it away.",
  "I am capable and will succeed.",
  "I believe in my ability and strength.",
  "Others genuinely like me.",
  "I respect all aspects of myself and behave accordingly.",
  "I honor my existence on this earth.",
  "I am unique and have special ideas.",
  "I have an amazing life.",
  "I have much to be grateful for.",
  "I am competent and skilled.",
  "I am prepared and will not falter.",
  "People listen when I speak.",
  "My ideas are great ones.",
  "I am grounded, mindful, and focused in all I do.",
  "I radiate positivity and attract the same energy.",
  "I choose peace over perfection.",
  "My presence brings calm to those around me.",
  "I let go of what no longer serves me.",
  "I am resilient, strong, and brave.",
  "My thoughts are filled with empowering beliefs.",
  "I am becoming more aligned with my purpose each day.",
  "I let myself rest when I need to.",
  "I create space for joy and ease in my life.",
  "I am doing the best I can, and that is enough.",
  "I trust that everything unfolds in perfect timing.",
  "My self-worth is not defined by external achievements.",
  "I choose love over fear.",
  "I grow through every experience.",
  "I am free to express myself authentically.",
  "I nourish my body, mind, and soul with care.",
  "I am connected to an infinite source of creativity.",
  "I listen to my inner wisdom with trust and patience.",
  "I deserve to take up space and speak my truth.",
  "I am in tune with the natural flow of life.",
  "I celebrate my uniqueness and share it confidently.",
  "Every breath I take fills me with calm and clarity.",
  "I treat myself with tenderness and respect.",
  "I am attracting new possibilities and positive change.",
  "I choose progress, not perfection.",
  "I am safe to be vulnerable and open-hearted.",
  "My energy is sacred, and I protect it wisely.",
  "I give myself permission to say no without guilt.",
  "I honor the journey, not just the destination.",
  "I find strength in stillness and silence.",
  "I am proud of how far I’ve come.",
  "I welcome growth, even when it’s uncomfortable.",
  "I deserve time for joy, fun, and laughter.",
  "I trust that the universe supports my path.",
  "I am not behind—my pace is perfect for me.",
  "I am a magnet for peaceful experiences.",
  "I am worthy of all the love and good coming my way.",
  "I embrace my emotions without judgment.",
  "I thrive in alignment with my true self.",
  "I make space for healing and self-discovery.",
  "I am grateful for who I am becoming.",
  "I hold compassion for myself in all circumstances.",
  "I speak kindly to and about myself.",
  "I am open to receiving unexpected blessings.",
  "I am supported, even when I can’t see it yet.",
  "My dreams are valid and achievable.",
  "I attract clarity, confidence, and calm.",
  "I honor both my light and my shadow.",
  "I am rewriting my story with courage and intention.",
];
